all:
  children:
    app_servers:
      hosts:
        target-vm:
          ansible_host: 192.168.122.53
          ansible_user: dev
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: "{{ VM_PASS }}"